# Generated by Django 2.2.5 on 2020-07-22 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='tb_books',
        ),
        migrations.AlterModelTable(
            name='heroinfo',
            table='tb_heros',
        ),
    ]
